<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?=$this->headTitle($this->translate('Michal Gacki developer test for Work Angel'))->setSeparator(' - ')->setAutoEscape(false)?>
        <?=$this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <link href="<?=$this->basePath().'/css/style.css'?>" rel="stylesheet" type="text/css">
        <?=$this->headScript()
            ->prependFile($this->basePath().'/js/frontend.js')
            ->prependFile('https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.3/angular.min.js')
        ?>
    </head>
    <body>
        <div id="content">
            <?=$this->content?>
        </div>
        <header>
            <nav>
                <ul>
                    <li><a href="<?=$this->url('home')?>"><?=$this->translate('Home')?></a></li>
                    <li><a href="#"><?=$this->translate('Reset')?></a></li>
                    <li><a href="view-source:#"><?=$this->translate('View Source')?></a></li>
                </ul>
            </nav>
        </header>
        <footer>
            <div id="footer">
                <p>&copy; 2014 Created by Michal Gacki</p>
            </div>
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
