<?php
$title = 'Create your wallet';
$this->headTitle($title);
?>
<a href="<?=$this->url('user', array('action' => 'logout'))?>"><?=$this->translate('Logout')?></a>
<h1><?=$this->escapeHtml($title)?></h1>
<?php
$form->setAttribute('action', $this->url('wallet', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
