<?php
$title = 'Your wallet';
$this->headTitle($title);
?>
<a href="<?=$this->url('user', array('action' => 'logout'))?>"><?=$this->translate('Logout')?></a>
<h1><?=$this->escapeHtml($title)?></h1>
<p><a href="<?=$this->url('wallet', array('action' => 'new'))?>"><?=$this->translate('Add new amount')?> (<?=$currency->getCodeAlternative()?>)</a></p>

<table class="table">
 <tr>
     <th><?=$this->translate('Date added')?></th>
     <th><?=$this->translate('Amount')?></th>
     <th><?=$this->translate('Options')?></th>
 </tr>
 <?php foreach ($items as $item) : ?>
 <tr>
     <td><?=$this->escapeHtml($item->getDateCreated())?></td>
     <td><?=$this->escapeHtml(number_format($item->getAmount()))?> <?=$currency->getCodeAlternative()?></td>
     <td><a href="#">Remove</a></td>
 </tr>
 <?php endforeach; ?>
 <tr>
     <td><?=$this->translate('Grand total:')?></td>
     <td colspan="2"><?=$total?> <i class="<?=$currency->getFontSymbol()?>"></i></td>
 </tr>
</table>

<h1 style="margin-top: 50px;"><?=$this->translate('Amount removed from your wallet')?></h1>

<table class="table">
 <tr>
     <th><?=$this->translate('Date added')?></th>
     <th><?=$this->translate('Amount')?></th>
     <th><?=$this->translate('Options')?></th>
 </tr>
 <?php foreach ($items_removed as $item) : ?>
 <tr>
     <td><?=$this->escapeHtml($item->getDateRemoved())?></td>
     <td><?=$this->escapeHtml(number_format($item->getAmount()))?> <?=$currency->getCodeAlternative()?></td>
 </tr>
 <?php endforeach; ?>
</table>