<?php
$title = 'Your wallet';
$this->headTitle($title);
?>
<a href="<?= $this->url('user', array('action' => 'logout')) ?>"><?= $this->translate('Logout') ?></a>
<h1><?= $this->escapeHtml($title) ?></h1>
<div style="color: red;">{{errorMessage}}</div>
<table class="table" cellpadding="0" cellspacing="0">
    <tr>
        <th><?= $this->translate('Date added') ?></th>
        <th><?= $this->translate('Amount') ?></th>
        <th><?= $this->translate('Options') ?></th>
    </tr>
    <tr>
        <td><?= $this->translate('Add new:') ?></td>
        <td colspan="2"><input type="text" value="0" ng-model="newItem.amount"> <?= $currency->getCodeAlternative() ?> <button ng-click="new(newItem)"><?= $this->translate('Add') ?></button></td>
    </tr>
    <tr ng-repeat="item in itemsActive">
        <td>{{item.dateCreated}}</td>
        <td>{{item.amount}} <?= $currency->getCodeAlternative() ?></td>
        <td><a href ng-click="remove(item.id)"><?= $this->translate('Remove') ?></a></td>
    </tr>
    <tr>
        <td><?= $this->translate('Grand total:') ?></td>
        <td colspan="2">{{grandTotal()}} <i class="<?= $currency->getFontSymbol() ?>"></i></td>
    </tr>
</table>

<h1 style="margin-top: 50px;"><?= $this->translate('Amount removed from your wallet') ?></h1>

<table class="table">
    <tr>
        <th><?= $this->translate('Date removed') ?></th>
        <th><?= $this->translate('Amount') ?></th>
    </tr>
    <tr ng-repeat="item in itemsRemoved">
        <td>{{item.dateRemoved}}</td>
        <td>{{item.amount}} <?= $currency->getCodeAlternative() ?></td>
    </tr>
</table>